permissions:
  contents: read # required for checkout

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  merge_group:
    types: [checks_requested]

jobs:
  continuous-integration:
    runs-on: [self-hosted, linux, build, elastic]
    continue-on-error: false
    timeout-minutes: 10
    concurrency:
      group: "bazel-${{ github.head_ref || github.run_id }}"
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
